language: python
sudo: required
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get python-pip
  - mkdir ~/.azure
  - touch ~/.azure/credentials
  - printf "[default]\nsubscription_id=${AZURE_SUBSCRIPTION_ID}\nclient_id=${AZURE_CLIENT_ID}\nsecret=${AZURE_SECRET}\ntenant=${AZURE_TENANT}" >> ~/.azure/credentials
  - sudo pip install ansible[azure]
script:
  - ansible-playbook clear_all.yml
