language: python
python:
  - "2.7"
script:
  - git remote add upstream https://github.com/ansible/ansible.git
  - git fetch upstream -p
  - git checkout upstream/devel
  - git pull upstream devel
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git remote add pages https://${github_token}@github.com/VSChina/ansible.git
  - git branch
  - git push pages devel:devel
